# Generated by Django 5.0.2 on 2024-03-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_chatroom_options_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Chat Message'},
        ),
    ]
